[package]
name = "myte"
version = "0.1.0"
authors = ["Heru Handika <herubiolog@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.*"
chrono = "0.4.*"
glob = "0.3.*"
rayon = "1.5.*"
spinners = "1.2.*"
