[package]
name = "myte"
version = "0.4.0"
authors = ["Heru Handika <herubiolog@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.*"
chrono = "0.4.*"
glob = "0.3.*"
num_cpus = "1.13.*"
rayon = "1.5.*"
indicatif = "0.16.*"
sysinfo = "0.16.*"

