name: Release

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [linux, macos]

        include:
          - name: linux
            os: ubuntu-latest
            executable: myte
            artifact_name: target/release/myte
            asset_name: myte-Linux-x86_64.zip

          - name: macos
            os: macos-latest
            executable: myte
            artifact_name: target/release/myte
            asset_name: myte-MacOS-x86_64.zip

    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Build
        run: |
          cargo build --release
          strip ${{ matrix.artifact_name }}
          mv ${{ matrix.artifact_name }} .
      
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: ${{ matrix.executable }}
          filename: ${{ matrix.asset_name }}

      - name: Upload Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload --clobber ${{ steps.get_version.outputs.version }} ${{ matrix.asset_name }}